/* Eigenständiges Atelierbuch. ES5; keine externen Laufzeitdienste. */
(function () {
  'use strict';
  var M = window.MAKINGOF = {}, shell, stage, wrap, counter, progress, prev, next, read, extra;
  var index = 0, back, modal = null, focusBefore = null, timer = null, resizeHandler, keyHandler, visibilityHandler;
  var audioContext = null, sounds = [], touch = null, suppressClickUntil = 0, modalCleanup = null;
  function el(tag, cls, parent, text) { var e = document.createElement(tag); e.className = cls || ''; if (text !== undefined) e.textContent = text; if (parent) parent.appendChild(e); return e; }
  function button(parent, text, fn, name) { var b = el('button', 'mo-btn', parent, text); b.type = 'button'; b.onclick = fn; if (name) b.setAttribute('data-mo', name); return b; }
  function data() { return window.MAKING_OF; }
  function src(name) { return data().base + name + (/^initial_/.test(name) ? '.png' : data().extension); }
  function remember() { try { localStorage.setItem('omsi.makingof.seite', String(index)); } catch (e) {} }
  function reduced() { return window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches; }
  function stopLoop() { if (timer) clearInterval(timer); timer = null; }
  function stopSounds() { sounds.forEach(function (s) { try { s.stop(); } catch (e) {} }); sounds = []; }
  function figure(parent, name, alt) { var b = el('button', 'mo-image-btn', parent); b.type = 'button'; b.setAttribute('aria-label', alt + ' vergrößern'); var img = el('img', '', b); img.alt = alt; img.src = src(name); img.draggable = false; b.onclick = function () { if (Date.now() > suppressClickUntil) zoom(name, alt); }; return b; }
  function paragraph(parent, text) { var p = el('p', 'mo-text', parent); var c = text.charAt(0); if ('ADEIMW'.indexOf(c) >= 0) { var initial = el('img', 'mo-initial', p); initial.src = src('initial_' + c); initial.alt = c; p.appendChild(document.createTextNode(text.slice(1))); } else p.textContent = text; return p; }
  M.makeSpread = function (n, parent) {
    var d = data().pages[n], s = el('article', 'mo-spread mo-layout-' + d.layout, parent); s.setAttribute('data-page', n); s.setAttribute('aria-label', d.title);
    var r = el('div', 'mo-running', s); el('span', '', r, d.chapter); el('span', '', r, 'Das Atelierbuch');
    var art = el('div', 'mo-art', s); d.art.split('|').forEach(function (a, i) { figure(art, a, d.title + (d.art.indexOf('|') >= 0 ? ' · Ansicht ' + (i + 1) : '')); });
    var copy = el('div', 'mo-copy', s); el('div', 'mo-kicker', copy, n === 0 ? 'Kevin · Für Omsi' : ('Werkstattblatt ' + ('0' + (n + 1)).slice(-2))); el('h1', 'mo-title', copy, d.title); el('p', 'mo-deck', copy, d.deck); if (d.layout === 'cover' || d.layout === 'closing') el('p', 'mo-text', copy, d.text); else paragraph(copy, d.text);
    el('div', 'mo-caption', s, d.caption); el('div', 'mo-ornament', s);
    var folio = el('div', 'mo-folio', s); el('span', '', folio, ('0' + (n * 2 + 1)).slice(-2)); el('span', 'mo-folio-center', folio, n === 0 ? 'Die Entstehung einer Geburtstagsgeschichte' : 'Bevor der Pfannekuchen fliegt'); el('span', '', folio, ('0' + (n * 2 + 2)).slice(-2));
    return s;
  };
  function fit() { if (!stage || !wrap) return; var w = stage.clientWidth - 20, h = stage.clientHeight - 18, scale = Math.max(.1, Math.min(w / 1440, h / 1080)); wrap.style.width = (1440 * scale) + 'px'; wrap.style.height = (1080 * scale) + 'px'; var s = wrap.firstChild; if (s) s.style.transform = 'scale(' + scale + ')'; }
  function render() {
    if (!wrap) return; while (wrap.firstChild) wrap.removeChild(wrap.firstChild); M.makeSpread(index, wrap); fit();
    counter.textContent = (index + 1) + ' / ' + data().pages.length; counter.setAttribute('aria-label', 'Doppelseite ' + (index + 1) + ' von ' + data().pages.length);
    prev.disabled = index === 0; next.disabled = index === data().pages.length - 1; progress.style.width = ((index + 1) / data().pages.length * 100) + '%';
    extra.style.display = data().pages[index].bonus ? '' : 'none'; extra.textContent = bonusLabel(data().pages[index].bonus); remember();
    // Only preload the next spread; keep the large archive economical on older iPads.
    if (data().pages[index + 1]) data().pages[index + 1].art.split('|').forEach(function (a) { var img = new Image(); img.src = src(a); });
  }
  M.go = function (n) { if (!wrap) return; closeModal(); var old = index; index = Math.max(0, Math.min(data().pages.length - 1, n)); render(); if (old !== index && !reduced()) { wrap.className = 'mo-book-wrap'; void wrap.offsetWidth; wrap.className = 'mo-book-wrap ' + (index > old ? 'mo-turn-next' : 'mo-turn-prev'); } };
  M.starten = function (parent, onBack) {
    M.stoppen(); back = onBack; index = 0; try { index = parseInt(localStorage.getItem('omsi.makingof.seite'), 10) || 0; } catch (e) {} index = Math.max(0, Math.min(data().pages.length - 1, index));
    shell = el('section', 'mo-shell', parent); shell.setAttribute('aria-label', 'Das Atelierbuch');
    var bar = el('header', 'mo-bar', shell); button(bar, '‹ Küche', function () { if (back) back(); }, 'back'); el('div', 'mo-bar-title', bar, data().title); button(bar, 'Register', contents, 'toc');
    el('div', 'mo-portrait-hint', shell, 'Quer gehalten werden die Doppelseiten größer. „Lesen“ öffnet den Text.');
    stage = el('div', 'mo-stage', shell); wrap = el('div', 'mo-book-wrap', stage);
    var bottom = el('footer', 'mo-bottom', shell); prev = button(bottom, '‹ Zurück', function () { M.go(index - 1); }, 'prev');
    var actions = el('div', 'mo-actions', bottom); read = button(actions, 'Lesen', reading, 'read'); extra = button(actions, 'Zugabe', bonus, 'bonus'); extra.className += ' mo-bonus'; counter = el('span', 'mo-counter', actions); counter.setAttribute('aria-live', 'polite');
    next = button(bottom, 'Weiter ›', function () { M.go(index + 1); }, 'next'); progress = el('i', '', el('div', 'mo-page-progress', shell));
    stage.addEventListener('touchstart', function (e) { if (e.touches.length !== 1) { touch = null; return; } touch = {x:e.touches[0].clientX,y:e.touches[0].clientY,t:Date.now()}; }, {passive:true});
    stage.addEventListener('touchend', function (e) { if (!touch || !e.changedTouches.length) return; var dx = e.changedTouches[0].clientX - touch.x, dy = e.changedTouches[0].clientY - touch.y, dt = Date.now() - touch.t; touch = null; if (Math.abs(dx) > 55 && Math.abs(dx) > Math.abs(dy) * 1.5 && dt < 1300) { suppressClickUntil = Date.now() + 500; M.go(index + (dx < 0 ? 1 : -1)); } }, {passive:true});
    stage.addEventListener('touchcancel', function () { touch = null; });
    resizeHandler = fit; window.addEventListener('resize', resizeHandler);
    keyHandler = function (e) { if (modal) { if (e.key === 'Escape') { e.preventDefault(); closeModal(); } else if (e.key === 'Tab') trapFocus(e); return; } if (/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)) return; if (e.key === 'ArrowRight') { e.preventDefault(); M.go(index + 1); } if (e.key === 'ArrowLeft') { e.preventDefault(); M.go(index - 1); } if (e.key === 'Home') M.go(0); if (e.key === 'End') M.go(data().pages.length - 1); };
    document.addEventListener('keydown', keyHandler);
    visibilityHandler = function () { if (document.hidden) { stopLoop(); stopSounds(); if (modal) { var status = modal.querySelector('.mo-status'); if (status) status.textContent = 'Pausiert · mit „Start“ fortsetzen'; var start = modal.querySelector('[data-mo="loop"]'); if (start) start.textContent = 'Start'; } } }; document.addEventListener('visibilitychange', visibilityHandler);
    render();
  };
  M.stoppen = function () { closeModal(); stopLoop(); stopSounds(); if (resizeHandler) window.removeEventListener('resize', resizeHandler); if (keyHandler) document.removeEventListener('keydown', keyHandler); if (visibilityHandler) document.removeEventListener('visibilitychange', visibilityHandler); if (shell && shell.parentNode) shell.parentNode.removeChild(shell); shell = stage = wrap = null; touch = null; };
  function openModal(title) {
    closeModal(); focusBefore = document.activeElement; modal = el('section', 'mo-modal', document.body); modal.setAttribute('role', 'dialog'); modal.setAttribute('aria-modal', 'true'); modal.setAttribute('aria-label', title);
    if (shell) shell.setAttribute('aria-hidden', 'true'); var head = el('header', 'mo-modal-head', modal); el('h2', '', head, title); var close = button(head, 'Schließen ×', closeModal, 'close'); var body = el('div', 'mo-modal-body', modal); close.focus(); return body;
  }
  function closeModal() { stopLoop(); stopSounds(); if (modalCleanup) { modalCleanup(); modalCleanup = null; } if (modal && modal.parentNode) modal.parentNode.removeChild(modal); modal = null; if (shell) shell.removeAttribute('aria-hidden'); if (focusBefore && document.documentElement.contains(focusBefore)) focusBefore.focus(); focusBefore = null; }
  function trapFocus(e) { var list = modal.querySelectorAll('button, input, a[href], [tabindex="0"]'); if (!list.length) return; var first = list[0], last = list[list.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } }
  function reading() { var d = data().pages[index], box = el('article', 'mo-reading', openModal(d.title)); el('h3', '', box, d.title); el('p', 'mo-lead', box, d.text); d.notes.split('\n\n').forEach(function (p) { el('p', '', box, p); }); el('small', '', box, d.caption); }
  function contents() { var grid = el('div', 'mo-toc', openModal('Auf dem Küchentisch · Das Register')); data().pages.forEach(function (d, n) { var b = el('button', 'mo-toc-entry', grid); b.type = 'button'; el('b', '', b, ('0' + (n + 1)).slice(-2)); var t = el('span', '', b); el('small', '', t, d.chapter); el('span', '', t, d.title); if (n === index) b.setAttribute('aria-current', 'page'); b.onclick = function () { M.go(n); }; }); }
  function zoom(name, title) { var body = openModal(title), tools = el('div', 'mo-zoom-tools', body); el('span', '', tools, 'Vergrößerung'); var slider = el('input', '', tools); slider.type = 'range'; slider.min = 100; slider.max = 300; slider.value = 100; slider.setAttribute('aria-label', 'Bildvergrößerung'); var value = el('span', '', tools, '100 %'); var pane = el('div', 'mo-zoom-pane', body), sheet = el('div', 'mo-zoom-sheet', pane), img = el('img', '', sheet); img.src = src(name); img.alt = title; slider.oninput = function () { sheet.style.width = slider.value + '%'; value.textContent = slider.value + ' %'; }; }
  function bonusLabel(b) { return {house:'Haus aufklappen',agent:'Akte öffnen',recipe:'Ecke anheben',compare:'Bilder vergleichen',boil:'Papierlabor',sound:'Klangpult',shadow:'Lichtprobe'}[b] || 'Zugabe'; }
  function bonus() { var type = data().pages[index].bonus, body = openModal(bonusLabel(type)), box = el('div', 'mo-bonus-sheet', body); if (type === 'house') house(box); else if (type === 'recipe') recipe(box); else if (type === 'agent') agent(box); else if (type === 'boil') boil(box); else if (type === 'compare') compare(box); else if (type === 'sound') soundLab(box); else if (type === 'shadow') shadow(box); }
  function house(box) { el('h3', '', box, 'Vier Räume, vier Erinnerungen'); var h = el('div', 'mo-house', box), img = el('img', '', h); img.src = src('11_haus_schnitt'); img.alt = 'Aufgeschnittenes Geschichtenhaus'; var rooms = [['Schlafzimmer','Hier beginnt die heimliche Mission. Ein grünes Katzenauge prüft, ob Kevin wirklich leise genug ist.'],['Keyboard','Unter einer Decke wartet das tiefe DÖÖM von damals. Die Katze kennt noch ein paar andere Tasten.'],['Küche','Alle Wege führen an diesen Tisch. Erst liegen hier Zutaten. Zum Schluss stehen zwei Teller bereit.'],['Keller','Im kühlen Keller wartet die Marmelade. Ein kleiner Vorrat, der die Erinnerung an den Sommer bewahrt.']]; var note = el('p', 'mo-room-note', box, 'Tippe auf ein Zimmer.'); rooms.forEach(function (r) { var b = el('button', 'mo-room', h, r[0]); b.type = 'button'; b.setAttribute('aria-pressed', 'false'); b.onclick = function () { var bs = h.querySelectorAll('button'); for (var i = 0; i < bs.length; i++) bs[i].setAttribute('aria-pressed', 'false'); b.setAttribute('aria-pressed', 'true'); note.textContent = r[1]; }; }); }
  function recipe(box) { var card = el('div', 'mo-recipe-card', box); el('h3', '', card, 'Omsis Pfannekuchen'); el('p', '', card, 'Mehl · Ei · Milch · eine Prise Salz'); el('p', '', card, 'Butter für die Pfanne. Marmelade für danach.'); var secret = el('div', 'mo-secret', card); secret.setAttribute('aria-live', 'polite'); var fold = el('button', 'mo-fold', card, 'Die Ecke anheben ↗'); fold.type = 'button'; fold.onclick = function () { secret.textContent = '… und jemand, der mitisst.'; fold.textContent = 'Die letzte Zutat ♥'; fold.disabled = true; }; el('p', '', box, 'Ein Rezeptfund aus der Geschichte.'); }
  function agent(box) { var card = el('div', 'mo-agent-card', box); el('small', '', card, 'STRENG GEHEIM'); el('strong', '', card, 'ZUGANG NUR FÜR 007'); el('p', '', card, 'Mission: Ein Pfannekuchen für Omsi.'); var status = el('p', 'mo-status', card, 'Genehmigung durch M steht aus.'); button(card, 'M um Genehmigung bitten', function () { status.textContent = 'GENEHMIGT. Die Küche wartet.'; card.style.transform = 'rotate(1deg)'; }); }
  function boil(box) {
    el('h3', '', box, 'Das Papier atmet'); var img = el('img', 'mo-lab-image', box); img.alt = 'Pfannekuchen in zwei wechselnden Zeichnungen'; var root = 'bilder/extras/hochkant/', frames = ['pfannkuchen-01.png','pfannkuchen-02.png']; var f = 0, fps = 8; img.src = root + frames[0]; var controls = el('div', 'mo-lab-controls', box), start = button(controls, 'Start', toggle, 'loop'); var step = button(controls, 'Einzelbild', function () { stopLoop(); start.textContent = 'Start'; advance(); }); var label = el('label', '', controls, '8 Bilder / Sekunde'); var slider = el('input', '', box); slider.type = 'range'; slider.min = 4; slider.max = 12; slider.step = 4; slider.value = 8; slider.setAttribute('aria-label', 'Bildwechsel pro Sekunde'); var status = el('p', 'mo-status', box, 'Bild 1 von 2 · Gleiche Mitte, leicht andere Zeichnung');
    function advance() { f = (f + 1) % frames.length; img.src = root + frames[f]; status.textContent = 'Bild ' + (f + 1) + ' von 2 · ' + fps + ' Wechsel pro Sekunde'; }
    function run() { stopLoop(); timer = setInterval(advance, 1000 / fps); start.textContent = 'Pause'; }
    function toggle() { if (timer) { stopLoop(); start.textContent = 'Start'; } else run(); }
    slider.oninput = function () { fps = +slider.value; label.textContent = fps + ' Bilder / Sekunde'; if (timer) run(); };
    frames.forEach(function (f) { var im = new Image(); im.src = root + f; }); if (!reduced()) run();
  }
  function compare(box) { el('h3', '', box, 'Skizze und ausgearbeitete Studie'); var panel = el('div', 'mo-compare', box), finished = el('img', '', panel); finished.src = src('19_zutaten_prozess'); finished.alt = 'Ausgearbeitete Zutatenstudie'; var over = el('div', 'mo-compare-over', panel), raw = el('img', '', over); raw.src = src('19_zutaten_prozess'); raw.alt = 'Bleistiftstudie derselben Zutaten'; var slider = el('input', '', box); slider.type = 'range'; slider.min = 0; slider.max = 100; slider.value = 50; slider.setAttribute('aria-label', 'Anteil der Bleistiftstudie'); el('p', '', box, 'Links: Bleistift. Rechts: Farbe und Papierstruktur.'); function width() { var w = panel.clientWidth, h = w * .75; panel.style.height = h + 'px'; raw.style.width = finished.style.width = (w * 2) + 'px'; raw.style.height = finished.style.height = (h * 2) + 'px'; finished.style.left = -w + 'px'; finished.style.top = -h + 'px'; } width(); window.addEventListener('resize', width); modalCleanup = function () { window.removeEventListener('resize', width); }; slider.oninput = function () { over.style.width = slider.value + '%'; }; }
  function shadow(box) { el('h3', '', box, 'Der kleine Kevin wächst'); var s = el('div', 'mo-shadow-stage', box), im = el('img', '', s); im.src = 'bilder/schatten/kevin-klein-profil.png'; im.alt = 'Kevins Schattenfigur'; var slider = el('input', '', box); slider.type = 'range'; slider.min = 70; slider.max = 170; slider.value = 100; slider.setAttribute('aria-label', 'Größe des Schattens'); slider.oninput = function () { im.style.transform = 'scale(' + (+slider.value / 100) + ')'; }; el('p', '', box, 'Näher an der Lampe wird der Schatten größer. Bewege den Regler und lass die Erinnerung wachsen.'); }
  function soundLab(box) { el('h3', '', box, 'Drei kleine Klangversuche'); var controls = el('div', 'mo-lab-controls', box), status = el('p', 'mo-status', box, 'Der Ton beginnt erst beim Antippen.'); [['Pfanne','sizzle'],['DÖÖM','doom'],['Katzentasten','cat']].forEach(function (a) { button(controls, a[0], function () { playSound(a[1], status); }); }); button(controls, 'Stopp', function () { stopSounds(); status.textContent = 'Still in der Küche.'; }); el('p', '', box, 'Stilisierte Geräusche aus dem kleinen Klanglabor.'); }
  function playSound(kind, status) { stopSounds(); var C = window.AudioContext || window.webkitAudioContext; if (!C) { status.textContent = 'Dieses Gerät unterstützt das Klanglabor nicht.'; return; } if (!audioContext) audioContext = new C(); if (audioContext.state === 'suspended') audioContext.resume(); var t = audioContext.currentTime;
    function tone(freq, offset, duration) { var o = audioContext.createOscillator(), g = audioContext.createGain(); o.type = 'triangle'; o.frequency.value = freq; g.gain.setValueAtTime(0, t + offset); g.gain.linearRampToValueAtTime(.12, t + offset + .02); g.gain.exponentialRampToValueAtTime(.001, t + offset + duration); o.connect(g); g.connect(audioContext.destination); o.start(t + offset); o.stop(t + offset + duration); sounds.push(o); o.onended = function () { o.disconnect(); g.disconnect(); }; }
    if (kind === 'doom') { tone(65.41, 0, 2); tone(98, 0, 1.8); status.textContent = 'DÖÖM · Der große Auftritt.'; }
    else if (kind === 'cat') { [261.6, 311.1, 392, 277.2, 523.2].forEach(function (f, i) { tone(f, i * .19, .35); }); status.textContent = 'Die Katze kennt ihren eigenen Takt.'; }
    else { var buffer = audioContext.createBuffer(1, audioContext.sampleRate * 1.8, audioContext.sampleRate), a = buffer.getChannelData(0); for (var i = 0; i < a.length; i++) a[i] = (Math.random() * 2 - 1) * (Math.random() > .996 ? 1 : .18); var source = audioContext.createBufferSource(), filter = audioContext.createBiquadFilter(), gain = audioContext.createGain(); source.buffer = buffer; filter.type = 'highpass'; filter.frequency.value = 900; gain.gain.setValueAtTime(.08, t); gain.gain.linearRampToValueAtTime(.001, t + 1.8); source.connect(filter); filter.connect(gain); gain.connect(audioContext.destination); source.start(); sounds.push(source); source.onended = function () { source.disconnect(); filter.disconnect(); gain.disconnect(); }; status.textContent = 'Die Butter wird heiß.'; }
  }
  M.dateien = function () { var files = ['css/making-of.css','js/making-of.js','daten/making-of.js','fonts/cormorant-400.ttf','fonts/cormorant-600.ttf','fonts/cormorant-700.ttf','fonts/source-sans-400.ttf','fonts/source-sans-600.ttf'], seen = {}; data().pages.forEach(function (p) { p.art.split('|').forEach(function (a) { seen[src(a)] = true; }); }); 'ADEIMW'.split('').forEach(function (c) { seen[src('initial_' + c)] = true; }); for (var k in seen) files.push(k); return files; };
})();
